# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kendall Koe
name: Kendall Koe
position: PhD Candidate
email: kfkoe2@illinois.edu
description: >-
  I am a PhD Candidate in the [Siebel School of Computing and Data Science](https://siebelschool.illinois.edu/) 
  at the [University of Illinois Urbana-Champaign](https://illinois.edu/). I am advised by [Dr. Girish Chowdhary](https://ece.illinois.edu/about/directory/faculty/girishc)
  in the [Distributed Autonomous Systems Laboratory](http://daslab.illinois.edu/) (DASLAB). I also collaborate with researchers in the [Monolithic Systems Lab](https://monolithicsystemslab.ise.illinois.edu/)
  as well as with researchers at [Iowa State University](https://www.iastate.edu/) as a part of the [COntext-Aware LEarning for Sustainable CybEr-agricultural](https://sites.google.com/view/coalescepreview/home?) (COALESCE) program.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kendallkoe.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kkoe2
google_scholar: N9JP9wkAAAAJ&hl
twitter: False

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
